services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - auth_api:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  
volumes:
  auth_api: {}
