version: '3.9'

networks:
  network: {}

services:
  database:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - auth_api:/var/lib/postgresql
    networks:
      - network
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    networks:
      - network
    restart: always

volumes:
  auth_api: {}
